# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Seed teachers
pwd = 'harryp'
User.delete_all
User.create!([{:name => 'Filius Flitwick',
               :email => 'filius@hogwarts.edu',
               :group => :teacher,
               :password => pwd,
               :password_confirmation => pwd},
              {:name => 'Minerva McGonagall',
               :email => 'minerva@hogwarts.edu',
               :group => :teacher,
               :password => pwd,
               :password_confirmation => pwd},
              {:name => 'Poppy Pomfrey',
               :email => 'poppy@hogwarts.edu',
               :group => :teacher,
               :password => pwd,
               :password_confirmation => pwd},
              {:name => 'Quirinus Quirrell',
               :email => 'quirinus@hogwarts.edu',
               :group => :teacher,
               :password => pwd,
               :password_confirmation => pwd},
              {:name => 'Horace Slughorn',
               :email => 'horace@hogwarts.edu',
               :group => :teacher,
               :password => pwd,
               :password_confirmation => pwd},
              {:name => 'Pomona Sprout',
               :email => 'pomona@hogwarts.edu',
               :group => :teacher,
               :password => pwd,
               :password_confirmation => pwd},
              {:name => 'Sybill Trelawney',
               :email => 'sybill@hogwarts.edu',
               :group => :teacher,
               :password => pwd,
               :password_confirmation => pwd},
              {:name => 'Albus Dumbledore',
               :email => 'albus@hogwarts.edu',
               :group => :teacher,
               :password => pwd,
               :password_confirmation => pwd},
              {:name => 'Rubeus Hagrid',
               :email => 'rubeus@hogwarts.edu',
               :group => :teacher,
               :password => pwd,
               :password_confirmation => pwd},
              {:name => 'Remus Lupin',
               :email => 'remus@hogwarts.edu',
               :group => :teacher,
               :password => pwd,
               :password_confirmation => pwd},
              {:name => 'Alastor Moody',
               :email => 'alastor@hogwarts.edu',
               :group => :teacher,
               :password => pwd,
               :password_confirmation => pwd},
              {:name => 'Severus Snape',
               :email => 'severus@hogwarts.edu',
               :group => :teacher,
               :password => pwd,
               :password_confirmation => pwd},
              {:name => 'Dolores Umbridge',
               :email => 'dolores@hogwarts.edu',
               :group => :teacher,
               :password => pwd,
               :password_confirmation => pwd}
             ])